package br.gov.go.camarajatai.sislegisold.suport;

import java.util.TreeMap;
import java.util.Map.Entry;

public class RomanNumber {

	private static TreeMap<Integer, String> numeros = null;
	private static TreeMap<String, Integer> romanos = null;
	
	private static char romanosBase[] = {'I', 'V', 'X', 'L', 'C', 'D', 'M'};
	
	public RomanNumber() {
		// TODO Auto-generated constructor stub
	}
	
	
	public static boolean isRoman(String value) {
		
		char[] str = value.toCharArray();
		boolean result;
		for (int i = 0; i < str.length; i++) {
			result = false;
			for (int j = 0; j < romanosBase.length; j++) {
				result = str[i] == romanosBase[j];
				
				if (result)
					break;
			}
			if (!result)
				return false;				
		}
		return true;
	}

	public static String getRoman(int number) {
		
		createMapStrings();
		
		Entry<Integer, String> entry = numeros.ceilingEntry(number);
		
		String result = entry == null ? "" : entry.getValue();
				
		return result;
		
	}

	public static int getNumber(String roman) {
		
		createMapStrings();
		
		Entry<String, Integer> entry = romanos.ceilingEntry(roman);
		
		int result = entry == null ? 0 : entry.getValue();
				
		return result;
		
	}
	

	
	
	private static void createMapStrings() {
		
		if (romanos != null)
			return;
		
		numeros = new TreeMap<Integer, String>();
		romanos = new TreeMap<String, Integer>();

		romanos.put("I",1); 
		romanos.put("II",2); 
		romanos.put("III",3); 
		romanos.put("IV",4); 
		romanos.put("V",5); 
		romanos.put("VI",6); 
		romanos.put("VII",7); 
		romanos.put("VIII",8); 
		romanos.put("IX",9); 
		romanos.put("X",10); 
		romanos.put("XI",11); 
		romanos.put("XII",12); 
		romanos.put("XIII",13); 
		romanos.put("XIV",14); 
		romanos.put("XV",15); 
		romanos.put("XVI",16); 
		romanos.put("XVII",17); 
		romanos.put("XVIII",18); 
		romanos.put("XIX",19); 
		romanos.put("XX",20); 
		romanos.put("XXI",21); 
		romanos.put("XXII",22); 
		romanos.put("XXIII",23); 
		romanos.put("XXIV",24); 
		romanos.put("XXV",25); 
		romanos.put("XXVI",26); 
		romanos.put("XXVII",27); 
		romanos.put("XXVIII",28); 
		romanos.put("XXIX",29); 
		romanos.put("XXX",30); 
		romanos.put("XXXI",31); 
		romanos.put("XXXII",32); 
		romanos.put("XXXIII",33); 
		romanos.put("XXXIV",34); 
		romanos.put("XXXV",35); 
		romanos.put("XXXVI",36); 
		romanos.put("XXXVII",37); 
		romanos.put("XXXVIII",38); 
		romanos.put("XXXIX",39); 
		romanos.put("XL",40); 
		romanos.put("XLI",41); 
		romanos.put("XLII",42); 
		romanos.put("XLIII",43); 
		romanos.put("XLIV",44); 
		romanos.put("XLV",45); 
		romanos.put("XLVI",46); 
		romanos.put("XLVII",47); 
		romanos.put("XLVIII",48); 
		romanos.put("XLIX",49); 
		romanos.put("L",50); 
		romanos.put("LI",51); 
		romanos.put("LII",52); 
		romanos.put("LIII",53); 
		romanos.put("LIV",54); 
		romanos.put("LV",55); 
		romanos.put("LVI",56); 
		romanos.put("LVII",57); 
		romanos.put("LVIII",58); 
		romanos.put("LIX",59); 
		romanos.put("LX",60); 
		romanos.put("LXI",61); 
		romanos.put("LXII",62); 
		romanos.put("LXIII",63); 
		romanos.put("LXIV",64); 
		romanos.put("LXV",65); 
		romanos.put("LXVI",66); 
		romanos.put("LXVII",67); 
		romanos.put("LXVIII",68); 
		romanos.put("LXIX",69); 
		romanos.put("LXX",70); 
		romanos.put("LXXI",71); 
		romanos.put("LXXII",72); 
		romanos.put("LXXIII",73); 
		romanos.put("LXXIV",74); 
		romanos.put("LXXV",75); 
		romanos.put("LXXVI",76); 
		romanos.put("LXXVII",77); 
		romanos.put("LXXVIII",78); 
		romanos.put("LXXIX",79); 
		romanos.put("LXXX",80); 
		romanos.put("LXXXI",81); 
		romanos.put("LXXXII",82); 
		romanos.put("LXXXIII",83); 
		romanos.put("LXXXIV",84); 
		romanos.put("LXXXV",85); 
		romanos.put("LXXXVI",86); 
		romanos.put("LXXXVII",87); 
		romanos.put("LXXXVIII",88); 
		romanos.put("LXXXIX",89); 
		romanos.put("XC",90); 
		romanos.put("XCI",91); 
		romanos.put("XCII",92); 
		romanos.put("XCIII",93); 
		romanos.put("XCIV",94); 
		romanos.put("XCV",95); 
		romanos.put("XCVI",96); 
		romanos.put("XCVII",97); 
		romanos.put("XCVIII",98); 
		romanos.put("XCIX",99); 
		romanos.put("C",100); 
		romanos.put("CI",101); 
		romanos.put("CII",102); 
		romanos.put("CIII",103); 
		romanos.put("CIV",104); 
		romanos.put("CV",105); 
		romanos.put("CVI",106); 
		romanos.put("CVII",107); 
		romanos.put("CVIII",108); 
		romanos.put("CIX",109); 
		romanos.put("CX",110); 
		romanos.put("CXI",111); 
		romanos.put("CXII",112); 
		romanos.put("CXIII",113); 
		romanos.put("CXIV",114); 
		romanos.put("CXV",115); 
		romanos.put("CXVI",116); 
		romanos.put("CXVII",117); 
		romanos.put("CXVIII",118); 
		romanos.put("CXIX",119); 
		romanos.put("CXX",120); 
		romanos.put("CXXI",121); 
		romanos.put("CXXII",122); 
		romanos.put("CXXIII",123); 
		romanos.put("CXXIV",124); 
		romanos.put("CXXV",125); 
		romanos.put("CXXVI",126); 
		romanos.put("CXXVII",127); 
		romanos.put("CXXVIII",128); 
		romanos.put("CXXIX",129); 
		romanos.put("CXXX",130); 
		romanos.put("CXXXI",131); 
		romanos.put("CXXXII",132); 
		romanos.put("CXXXIII",133); 
		romanos.put("CXXXIV",134); 
		romanos.put("CXXXV",135); 
		romanos.put("CXXXVI",136); 
		romanos.put("CXXXVII",137); 
		romanos.put("CXXXVIII",138); 
		romanos.put("CXXXIX",139); 
		romanos.put("CXL",140); 
		romanos.put("CXLI",141); 
		romanos.put("CXLII",142); 
		romanos.put("CXLIII",143); 
		romanos.put("CXLIV",144); 
		romanos.put("CXLV",145); 
		romanos.put("CXLVI",146); 
		romanos.put("CXLVII",147); 
		romanos.put("CXLVIII",148); 
		romanos.put("CXLIX",149); 
		romanos.put("CL",150); 
		romanos.put("CLI",151); 
		romanos.put("CLII",152); 
		romanos.put("CLIII",153); 
		romanos.put("CLIV",154); 
		romanos.put("CLV",155); 
		romanos.put("CLVI",156); 
		romanos.put("CLVII",157); 
		romanos.put("CLVIII",158); 
		romanos.put("CLIX",159); 
		romanos.put("CLX",160); 
		romanos.put("CLXI",161); 
		romanos.put("CLXII",162); 
		romanos.put("CLXIII",163); 
		romanos.put("CLXIV",164); 
		romanos.put("CLXV",165); 
		romanos.put("CLXVI",166); 
		romanos.put("CLXVII",167); 
		romanos.put("CLXVIII",168); 
		romanos.put("CLXIX",169); 
		romanos.put("CLXX",170); 
		romanos.put("CLXXI",171); 
		romanos.put("CLXXII",172); 
		romanos.put("CLXXIII",173); 
		romanos.put("CLXXIV",174); 
		romanos.put("CLXXV",175); 
		romanos.put("CLXXVI",176); 
		romanos.put("CLXXVII",177); 
		romanos.put("CLXXVIII",178); 
		romanos.put("CLXXIX",179); 
		romanos.put("CLXXX",180); 
		romanos.put("CLXXXI",181); 
		romanos.put("CLXXXII",182); 
		romanos.put("CLXXXIII",183); 
		romanos.put("CLXXXIV",184); 
		romanos.put("CLXXXV",185); 
		romanos.put("CLXXXVI",186); 
		romanos.put("CLXXXVII",187); 
		romanos.put("CLXXXVIII",188); 
		romanos.put("CLXXXIX",189); 
		romanos.put("CXC",190); 
		romanos.put("CXCI",191); 
		romanos.put("CXCII",192); 
		romanos.put("CXCIII",193); 
		romanos.put("CXCIV",194); 
		romanos.put("CXCV",195); 
		romanos.put("CXCVI",196); 
		romanos.put("CXCVII",197); 
		romanos.put("CXCVIII",198); 
		romanos.put("CXCIX",199); 
		romanos.put("CC",200); 
		romanos.put("CCI",201); 
		romanos.put("CCII",202); 
		romanos.put("CCIII",203); 
		romanos.put("CCIV",204); 
		romanos.put("CCV",205); 
		romanos.put("CCVI",206); 
		romanos.put("CCVII",207); 
		romanos.put("CCVIII",208); 
		romanos.put("CCIX",209); 
		romanos.put("CCX",210); 
		romanos.put("CCXI",211); 
		romanos.put("CCXII",212); 
		romanos.put("CCXIII",213); 
		romanos.put("CCXIV",214); 
		romanos.put("CCXV",215); 
		romanos.put("CCXVI",216); 
		romanos.put("CCXVII",217); 
		romanos.put("CCXVIII",218); 
		romanos.put("CCXIX",219); 
		romanos.put("CCXX",220); 
		romanos.put("CCXXI",221); 
		romanos.put("CCXXII",222); 
		romanos.put("CCXXIII",223); 
		romanos.put("CCXXIV",224); 
		romanos.put("CCXXV",225); 
		romanos.put("CCXXVI",226); 
		romanos.put("CCXXVII",227); 
		romanos.put("CCXXVIII",228); 
		romanos.put("CCXXIX",229); 
		romanos.put("CCXXX",230); 
		romanos.put("CCXXXI",231); 
		romanos.put("CCXXXII",232); 
		romanos.put("CCXXXIII",233); 
		romanos.put("CCXXXIV",234); 
		romanos.put("CCXXXV",235); 
		romanos.put("CCXXXVI",236); 
		romanos.put("CCXXXVII",237); 
		romanos.put("CCXXXVIII",238); 
		romanos.put("CCXXXIX",239); 
		romanos.put("CCXL",240); 
		romanos.put("CCXLI",241); 
		romanos.put("CCXLII",242); 
		romanos.put("CCXLIII",243); 
		romanos.put("CCXLIV",244); 
		romanos.put("CCXLV",245); 
		romanos.put("CCXLVI",246); 
		romanos.put("CCXLVII",247); 
		romanos.put("CCXLVIII",248); 
		romanos.put("CCXLIX",249); 
		romanos.put("CCL",250); 
		romanos.put("CCLI",251); 
		romanos.put("CCLII",252); 
		romanos.put("CCLIII",253); 
		romanos.put("CCLIV",254); 
		romanos.put("CCLV",255); 
		romanos.put("CCLVI",256); 
		romanos.put("CCLVII",257); 
		romanos.put("CCLVIII",258); 
		romanos.put("CCLIX",259); 
		romanos.put("CCLX",260); 
		romanos.put("CCLXI",261); 
		romanos.put("CCLXII",262); 
		romanos.put("CCLXIII",263); 
		romanos.put("CCLXIV",264); 
		romanos.put("CCLXV",265); 
		romanos.put("CCLXVI",266); 
		romanos.put("CCLXVII",267); 
		romanos.put("CCLXVIII",268); 
		romanos.put("CCLXIX",269); 
		romanos.put("CCLXX",270); 
		romanos.put("CCLXXI",271); 
		romanos.put("CCLXXII",272); 
		romanos.put("CCLXXIII",273); 
		romanos.put("CCLXXIV",274); 
		romanos.put("CCLXXV",275); 
		romanos.put("CCLXXVI",276); 
		romanos.put("CCLXXVII",277); 
		romanos.put("CCLXXVIII",278); 
		romanos.put("CCLXXIX",279); 
		romanos.put("CCLXXX",280); 
		romanos.put("CCLXXXI",281); 
		romanos.put("CCLXXXII",282); 
		romanos.put("CCLXXXIII",283); 
		romanos.put("CCLXXXIV",284); 
		romanos.put("CCLXXXV",285); 
		romanos.put("CCLXXXVI",286); 
		romanos.put("CCLXXXVII",287); 
		romanos.put("CCLXXXVIII",288); 
		romanos.put("CCLXXXIX",289); 
		romanos.put("CCXC",290); 
		romanos.put("CCXCI",291); 
		romanos.put("CCXCII",292); 
		romanos.put("CCXCIII",293); 
		romanos.put("CCXCIV",294); 
		romanos.put("CCXCV",295); 
		romanos.put("CCXCVI",296); 
		romanos.put("CCXCVII",297); 
		romanos.put("CCXCVIII",298); 
		romanos.put("CCXCIX",299); 
		romanos.put("CCC",300); 
		romanos.put("CCCI",301); 
		romanos.put("CCCII",302); 
		romanos.put("CCCIII",303); 
		romanos.put("CCCIV",304); 
		romanos.put("CCCV",305); 
		romanos.put("CCCVI",306); 
		romanos.put("CCCVII",307); 
		romanos.put("CCCVIII",308); 
		romanos.put("CCCIX",309); 
		romanos.put("CCCX",310); 
		romanos.put("CCCXI",311); 
		romanos.put("CCCXII",312); 
		romanos.put("CCCXIII",313); 
		romanos.put("CCCXIV",314); 
		romanos.put("CCCXV",315); 
		romanos.put("CCCXVI",316); 
		romanos.put("CCCXVII",317); 
		romanos.put("CCCXVIII",318); 
		romanos.put("CCCXIX",319); 
		romanos.put("CCCXX",320); 
		romanos.put("CCCXXI",321); 
		romanos.put("CCCXXII",322); 
		romanos.put("CCCXXIII",323); 
		romanos.put("CCCXXIV",324); 
		romanos.put("CCCXXV",325); 
		romanos.put("CCCXXVI",326); 
		romanos.put("CCCXXVII",327); 
		romanos.put("CCCXXVIII",328); 
		romanos.put("CCCXXIX",329); 
		romanos.put("CCCXXX",330); 
		romanos.put("CCCXXXI",331); 
		romanos.put("CCCXXXII",332); 
		romanos.put("CCCXXXIII",333); 
		romanos.put("CCCXXXIV",334); 
		romanos.put("CCCXXXV",335); 
		romanos.put("CCCXXXVI",336); 
		romanos.put("CCCXXXVII",337); 
		romanos.put("CCCXXXVIII",338); 
		romanos.put("CCCXXXIX",339); 
		romanos.put("CCCXL",340); 
		romanos.put("CCCXLI",341); 
		romanos.put("CCCXLII",342); 
		romanos.put("CCCXLIII",343); 
		romanos.put("CCCXLIV",344); 
		romanos.put("CCCXLV",345); 
		romanos.put("CCCXLVI",346); 
		romanos.put("CCCXLVII",347); 
		romanos.put("CCCXLVIII",348); 
		romanos.put("CCCXLIX",349); 
		romanos.put("CCCL",350); 
		romanos.put("CCCLI",351); 
		romanos.put("CCCLII",352); 
		romanos.put("CCCLIII",353); 
		romanos.put("CCCLIV",354); 
		romanos.put("CCCLV",355); 
		romanos.put("CCCLVI",356); 
		romanos.put("CCCLVII",357); 
		romanos.put("CCCLVIII",358); 
		romanos.put("CCCLIX",359); 
		romanos.put("CCCLX",360); 
		romanos.put("CCCLXI",361); 
		romanos.put("CCCLXII",362); 
		romanos.put("CCCLXIII",363); 
		romanos.put("CCCLXIV",364); 
		romanos.put("CCCLXV",365); 
		romanos.put("CCCLXVI",366); 
		romanos.put("CCCLXVII",367); 
		romanos.put("CCCLXVIII",368); 
		romanos.put("CCCLXIX",369); 
		romanos.put("CCCLXX",370); 
		romanos.put("CCCLXXI",371); 
		romanos.put("CCCLXXII",372); 
		romanos.put("CCCLXXIII",373); 
		romanos.put("CCCLXXIV",374); 
		romanos.put("CCCLXXV",375); 
		romanos.put("CCCLXXVI",376); 
		romanos.put("CCCLXXVII",377); 
		romanos.put("CCCLXXVIII",378); 
		romanos.put("CCCLXXIX",379); 
		romanos.put("CCCLXXX",380); 
		romanos.put("CCCLXXXI",381); 
		romanos.put("CCCLXXXII",382); 
		romanos.put("CCCLXXXIII",383); 
		romanos.put("CCCLXXXIV",384); 
		romanos.put("CCCLXXXV",385); 
		romanos.put("CCCLXXXVI",386); 
		romanos.put("CCCLXXXVII",387); 
		romanos.put("CCCLXXXVIII",388); 
		romanos.put("CCCLXXXIX",389); 
		romanos.put("CCCXC",390); 
		romanos.put("CCCXCI",391); 
		romanos.put("CCCXCII",392); 
		romanos.put("CCCXCIII",393); 
		romanos.put("CCCXCIV",394); 
		romanos.put("CCCXCV",395); 
		romanos.put("CCCXCVI",396); 
		romanos.put("CCCXCVII",397); 
		romanos.put("CCCXCVIII",398); 
		romanos.put("CCCXCIX",399); 
		romanos.put("CD",400); 
		romanos.put("CDI",401); 
		romanos.put("CDII",402); 
		romanos.put("CDIII",403); 
		romanos.put("CDIV",404); 
		romanos.put("CDV",405); 
		romanos.put("CDVI",406); 
		romanos.put("CDVII",407); 
		romanos.put("CDVIII",408); 
		romanos.put("CDIX",409); 
		romanos.put("CDX",410); 
		romanos.put("CDXI",411); 
		romanos.put("CDXII",412); 
		romanos.put("CDXIII",413); 
		romanos.put("CDXIV",414); 
		romanos.put("CDXV",415); 
		romanos.put("CDXVI",416); 
		romanos.put("CDXVII",417); 
		romanos.put("CDXVIII",418); 
		romanos.put("CDXIX",419); 
		romanos.put("CDXX",420); 
		romanos.put("CDXXI",421); 
		romanos.put("CDXXII",422); 
		romanos.put("CDXXIII",423); 
		romanos.put("CDXXIV",424); 
		romanos.put("CDXXV",425); 
		romanos.put("CDXXVI",426); 
		romanos.put("CDXXVII",427); 
		romanos.put("CDXXVIII",428); 
		romanos.put("CDXXIX",429); 
		romanos.put("CDXXX",430); 
		romanos.put("CDXXXI",431); 
		romanos.put("CDXXXII",432); 
		romanos.put("CDXXXIII",433); 
		romanos.put("CDXXXIV",434); 
		romanos.put("CDXXXV",435); 
		romanos.put("CDXXXVI",436); 
		romanos.put("CDXXXVII",437); 
		romanos.put("CDXXXVIII",438); 
		romanos.put("CDXXXIX",439); 
		romanos.put("CDXL",440); 
		romanos.put("CDXLI",441); 
		romanos.put("CDXLII",442); 
		romanos.put("CDXLIII",443); 
		romanos.put("CDXLIV",444); 
		romanos.put("CDXLV",445); 
		romanos.put("CDXLVI",446); 
		romanos.put("CDXLVII",447); 
		romanos.put("CDXLVIII",448); 
		romanos.put("CDXLIX",449); 
		romanos.put("CDL",450); 
		romanos.put("CDLI",451); 
		romanos.put("CDLII",452); 
		romanos.put("CDLIII",453); 
		romanos.put("CDLIV",454); 
		romanos.put("CDLV",455); 
		romanos.put("CDLVI",456); 
		romanos.put("CDLVII",457); 
		romanos.put("CDLVIII",458); 
		romanos.put("CDLIX",459); 
		romanos.put("CDLX",460); 
		romanos.put("CDLXI",461); 
		romanos.put("CDLXII",462); 
		romanos.put("CDLXIII",463); 
		romanos.put("CDLXIV",464); 
		romanos.put("CDLXV",465); 
		romanos.put("CDLXVI",466); 
		romanos.put("CDLXVII",467); 
		romanos.put("CDLXVIII",468); 
		romanos.put("CDLXIX",469); 
		romanos.put("CDLXX",470); 
		romanos.put("CDLXXI",471); 
		romanos.put("CDLXXII",472); 
		romanos.put("CDLXXIII",473); 
		romanos.put("CDLXXIV",474); 
		romanos.put("CDLXXV",475); 
		romanos.put("CDLXXVI",476); 
		romanos.put("CDLXXVII",477); 
		romanos.put("CDLXXVIII",478); 
		romanos.put("CDLXXIX",479); 
		romanos.put("CDLXXX",480); 
		romanos.put("CDLXXXI",481); 
		romanos.put("CDLXXXII",482); 
		romanos.put("CDLXXXIII",483); 
		romanos.put("CDLXXXIV",484); 
		romanos.put("CDLXXXV",485); 
		romanos.put("CDLXXXVI",486); 
		romanos.put("CDLXXXVII",487); 
		romanos.put("CDLXXXVIII",488); 
		romanos.put("CDLXXXIX",489); 
		romanos.put("CDXC",490); 
		romanos.put("CDXCI",491); 
		romanos.put("CDXCII",492); 
		romanos.put("CDXCIII",493); 
		romanos.put("CDXCIV",494); 
		romanos.put("CDXCV",495); 
		romanos.put("CDXCVI",496); 
		romanos.put("CDXCVII",497); 
		romanos.put("CDXCVIII",498); 
		romanos.put("CDXCIX",499); 
		romanos.put("D",500); 
		romanos.put("DI",501); 
		romanos.put("DII",502); 
		romanos.put("DIII",503); 
		romanos.put("DIV",504); 
		romanos.put("DV",505); 
		romanos.put("DVI",506); 
		romanos.put("DVII",507); 
		romanos.put("DVIII",508); 
		romanos.put("DIX",509); 
		romanos.put("DX",510); 
		romanos.put("DXI",511); 
		romanos.put("DXII",512); 
		romanos.put("DXIII",513); 
		romanos.put("DXIV",514); 
		romanos.put("DXV",515); 
		romanos.put("DXVI",516); 
		romanos.put("DXVII",517); 
		romanos.put("DXVIII",518); 
		romanos.put("DXIX",519); 
		romanos.put("DXX",520); 
		romanos.put("DXXI",521); 
		romanos.put("DXXII",522); 
		romanos.put("DXXIII",523); 
		romanos.put("DXXIV",524); 
		romanos.put("DXXV",525); 
		romanos.put("DXXVI",526); 
		romanos.put("DXXVII",527); 
		romanos.put("DXXVIII",528); 
		romanos.put("DXXIX",529); 
		romanos.put("DXXX",530); 
		romanos.put("DXXXI",531); 
		romanos.put("DXXXII",532); 
		romanos.put("DXXXIII",533); 
		romanos.put("DXXXIV",534); 
		romanos.put("DXXXV",535); 
		romanos.put("DXXXVI",536); 
		romanos.put("DXXXVII",537); 
		romanos.put("DXXXVIII",538); 
		romanos.put("DXXXIX",539); 
		romanos.put("DXL",540); 
		romanos.put("DXLI",541); 
		romanos.put("DXLII",542); 
		romanos.put("DXLIII",543); 
		romanos.put("DXLIV",544); 
		romanos.put("DXLV",545); 
		romanos.put("DXLVI",546); 
		romanos.put("DXLVII",547); 
		romanos.put("DXLVIII",548); 
		romanos.put("DXLIX",549); 
		romanos.put("DL",550); 
		romanos.put("DLI",551); 
		romanos.put("DLII",552); 
		romanos.put("DLIII",553); 
		romanos.put("DLIV",554); 
		romanos.put("DLV",555); 
		romanos.put("DLVI",556); 
		romanos.put("DLVII",557); 
		romanos.put("DLVIII",558); 
		romanos.put("DLIX",559); 
		romanos.put("DLX",560); 
		romanos.put("DLXI",561); 
		romanos.put("DLXII",562); 
		romanos.put("DLXIII",563); 
		romanos.put("DLXIV",564); 
		romanos.put("DLXV",565); 
		romanos.put("DLXVI",566); 
		romanos.put("DLXVII",567); 
		romanos.put("DLXVIII",568); 
		romanos.put("DLXIX",569); 
		romanos.put("DLXX",570); 
		romanos.put("DLXXI",571); 
		romanos.put("DLXXII",572); 
		romanos.put("DLXXIII",573); 
		romanos.put("DLXXIV",574); 
		romanos.put("DLXXV",575); 
		romanos.put("DLXXVI",576); 
		romanos.put("DLXXVII",577); 
		romanos.put("DLXXVIII",578); 
		romanos.put("DLXXIX",579); 
		romanos.put("DLXXX",580); 
		romanos.put("DLXXXI",581); 
		romanos.put("DLXXXII",582); 
		romanos.put("DLXXXIII",583); 
		romanos.put("DLXXXIV",584); 
		romanos.put("DLXXXV",585); 
		romanos.put("DLXXXVI",586); 
		romanos.put("DLXXXVII",587); 
		romanos.put("DLXXXVIII",588); 
		romanos.put("DLXXXIX",589); 
		romanos.put("DXC",590); 
		romanos.put("DXCI",591); 
		romanos.put("DXCII",592); 
		romanos.put("DXCIII",593); 
		romanos.put("DXCIV",594); 
		romanos.put("DXCV",595); 
		romanos.put("DXCVI",596); 
		romanos.put("DXCVII",597); 
		romanos.put("DXCVIII",598); 
		romanos.put("DXCIX",599); 
		romanos.put("DC",600); 
		romanos.put("DCI",601); 
		romanos.put("DCII",602); 
		romanos.put("DCIII",603); 
		romanos.put("DCIV",604); 
		romanos.put("DCV",605); 
		romanos.put("DCVI",606); 
		romanos.put("DCVII",607); 
		romanos.put("DCVIII",608); 
		romanos.put("DCIX",609); 
		romanos.put("DCX",610); 
		romanos.put("DCXI",611); 
		romanos.put("DCXII",612); 
		romanos.put("DCXIII",613); 
		romanos.put("DCXIV",614); 
		romanos.put("DCXV",615); 
		romanos.put("DCXVI",616); 
		romanos.put("DCXVII",617); 
		romanos.put("DCXVIII",618); 
		romanos.put("DCXIX",619); 
		romanos.put("DCXX",620); 
		romanos.put("DCXXI",621); 
		romanos.put("DCXXII",622); 
		romanos.put("DCXXIII",623); 
		romanos.put("DCXXIV",624); 
		romanos.put("DCXXV",625); 
		romanos.put("DCXXVI",626); 
		romanos.put("DCXXVII",627); 
		romanos.put("DCXXVIII",628); 
		romanos.put("DCXXIX",629); 
		romanos.put("DCXXX",630); 
		romanos.put("DCXXXI",631); 
		romanos.put("DCXXXII",632); 
		romanos.put("DCXXXIII",633); 
		romanos.put("DCXXXIV",634); 
		romanos.put("DCXXXV",635); 
		romanos.put("DCXXXVI",636); 
		romanos.put("DCXXXVII",637); 
		romanos.put("DCXXXVIII",638); 
		romanos.put("DCXXXIX",639); 
		romanos.put("DCXL",640); 
		romanos.put("DCXLI",641); 
		romanos.put("DCXLII",642); 
		romanos.put("DCXLIII",643); 
		romanos.put("DCXLIV",644); 
		romanos.put("DCXLV",645); 
		romanos.put("DCXLVI",646); 
		romanos.put("DCXLVII",647); 
		romanos.put("DCXLVIII",648); 
		romanos.put("DCXLIX",649); 
		romanos.put("DCL",650); 
		romanos.put("DCLI",651); 
		romanos.put("DCLII",652); 
		romanos.put("DCLIII",653); 
		romanos.put("DCLIV",654); 
		romanos.put("DCLV",655); 
		romanos.put("DCLVI",656); 
		romanos.put("DCLVII",657); 
		romanos.put("DCLVIII",658); 
		romanos.put("DCLIX",659); 
		romanos.put("DCLX",660); 
		romanos.put("DCLXI",661); 
		romanos.put("DCLXII",662); 
		romanos.put("DCLXIII",663); 
		romanos.put("DCLXIV",664); 
		romanos.put("DCLXV",665); 
		romanos.put("DCLXVI",666); 
		romanos.put("DCLXVII",667); 
		romanos.put("DCLXVIII",668); 
		romanos.put("DCLXIX",669); 
		romanos.put("DCLXX",670); 
		romanos.put("DCLXXI",671); 
		romanos.put("DCLXXII",672); 
		romanos.put("DCLXXIII",673); 
		romanos.put("DCLXXIV",674); 
		romanos.put("DCLXXV",675); 
		romanos.put("DCLXXVI",676); 
		romanos.put("DCLXXVII",677); 
		romanos.put("DCLXXVIII",678); 
		romanos.put("DCLXXIX",679); 
		romanos.put("DCLXXX",680); 
		romanos.put("DCLXXXI",681); 
		romanos.put("DCLXXXII",682); 
		romanos.put("DCLXXXIII",683); 
		romanos.put("DCLXXXIV",684); 
		romanos.put("DCLXXXV",685); 
		romanos.put("DCLXXXVI",686); 
		romanos.put("DCLXXXVII",687); 
		romanos.put("DCLXXXVIII",688); 
		romanos.put("DCLXXXIX",689); 
		romanos.put("DCXC",690); 
		romanos.put("DCXCI",691); 
		romanos.put("DCXCII",692); 
		romanos.put("DCXCIII",693); 
		romanos.put("DCXCIV",694); 
		romanos.put("DCXCV",695); 
		romanos.put("DCXCVI",696); 
		romanos.put("DCXCVII",697); 
		romanos.put("DCXCVIII",698); 
		romanos.put("DCXCIX",699); 
		romanos.put("DCC",700); 
		romanos.put("DCCI",701); 
		romanos.put("DCCII",702); 
		romanos.put("DCCIII",703); 
		romanos.put("DCCIV",704); 
		romanos.put("DCCV",705); 
		romanos.put("DCCVI",706); 
		romanos.put("DCCVII",707); 
		romanos.put("DCCVIII",708); 
		romanos.put("DCCIX",709); 
		romanos.put("DCCX",710); 
		romanos.put("DCCXI",711); 
		romanos.put("DCCXII",712); 
		romanos.put("DCCXIII",713); 
		romanos.put("DCCXIV",714); 
		romanos.put("DCCXV",715); 
		romanos.put("DCCXVI",716); 
		romanos.put("DCCXVII",717); 
		romanos.put("DCCXVIII",718); 
		romanos.put("DCCXIX",719); 
		romanos.put("DCCXX",720); 
		romanos.put("DCCXXI",721); 
		romanos.put("DCCXXII",722); 
		romanos.put("DCCXXIII",723); 
		romanos.put("DCCXXIV",724); 
		romanos.put("DCCXXV",725); 
		romanos.put("DCCXXVI",726); 
		romanos.put("DCCXXVII",727); 
		romanos.put("DCCXXVIII",728); 
		romanos.put("DCCXXIX",729); 
		romanos.put("DCCXXX",730); 
		romanos.put("DCCXXXI",731); 
		romanos.put("DCCXXXII",732); 
		romanos.put("DCCXXXIII",733); 
		romanos.put("DCCXXXIV",734); 
		romanos.put("DCCXXXV",735); 
		romanos.put("DCCXXXVI",736); 
		romanos.put("DCCXXXVII",737); 
		romanos.put("DCCXXXVIII",738); 
		romanos.put("DCCXXXIX",739); 
		romanos.put("DCCXL",740); 
		romanos.put("DCCXLI",741); 
		romanos.put("DCCXLII",742); 
		romanos.put("DCCXLIII",743); 
		romanos.put("DCCXLIV",744); 
		romanos.put("DCCXLV",745); 
		romanos.put("DCCXLVI",746); 
		romanos.put("DCCXLVII",747); 
		romanos.put("DCCXLVIII",748); 
		romanos.put("DCCXLIX",749); 
		romanos.put("DCCL",750); 
		romanos.put("DCCLI",751); 
		romanos.put("DCCLII",752); 
		romanos.put("DCCLIII",753); 
		romanos.put("DCCLIV",754); 
		romanos.put("DCCLV",755); 
		romanos.put("DCCLVI",756); 
		romanos.put("DCCLVII",757); 
		romanos.put("DCCLVIII",758); 
		romanos.put("DCCLIX",759); 
		romanos.put("DCCLX",760); 
		romanos.put("DCCLXI",761); 
		romanos.put("DCCLXII",762); 
		romanos.put("DCCLXIII",763); 
		romanos.put("DCCLXIV",764); 
		romanos.put("DCCLXV",765); 
		romanos.put("DCCLXVI",766); 
		romanos.put("DCCLXVII",767); 
		romanos.put("DCCLXVIII",768); 
		romanos.put("DCCLXIX",769); 
		romanos.put("DCCLXX",770); 
		romanos.put("DCCLXXI",771); 
		romanos.put("DCCLXXII",772); 
		romanos.put("DCCLXXIII",773); 
		romanos.put("DCCLXXIV",774); 
		romanos.put("DCCLXXV",775); 
		romanos.put("DCCLXXVI",776); 
		romanos.put("DCCLXXVII",777); 
		romanos.put("DCCLXXVIII",778); 
		romanos.put("DCCLXXIX",779); 
		romanos.put("DCCLXXX",780); 
		romanos.put("DCCLXXXI",781); 
		romanos.put("DCCLXXXII",782); 
		romanos.put("DCCLXXXIII",783); 
		romanos.put("DCCLXXXIV",784); 
		romanos.put("DCCLXXXV",785); 
		romanos.put("DCCLXXXVI",786); 
		romanos.put("DCCLXXXVII",787); 
		romanos.put("DCCLXXXVIII",788); 
		romanos.put("DCCLXXXIX",789); 
		romanos.put("DCCXC",790); 
		romanos.put("DCCXCI",791); 
		romanos.put("DCCXCII",792); 
		romanos.put("DCCXCIII",793); 
		romanos.put("DCCXCIV",794); 
		romanos.put("DCCXCV",795); 
		romanos.put("DCCXCVI",796); 
		romanos.put("DCCXCVII",797); 
		romanos.put("DCCXCVIII",798); 
		romanos.put("DCCXCIX",799); 
		romanos.put("DCCC",800); 
		romanos.put("DCCCI",801); 
		romanos.put("DCCCII",802); 
		romanos.put("DCCCIII",803); 
		romanos.put("DCCCIV",804); 
		romanos.put("DCCCV",805); 
		romanos.put("DCCCVI",806); 
		romanos.put("DCCCVII",807); 
		romanos.put("DCCCVIII",808); 
		romanos.put("DCCCIX",809); 
		romanos.put("DCCCX",810); 
		romanos.put("DCCCXI",811); 
		romanos.put("DCCCXII",812); 
		romanos.put("DCCCXIII",813); 
		romanos.put("DCCCXIV",814); 
		romanos.put("DCCCXV",815); 
		romanos.put("DCCCXVI",816); 
		romanos.put("DCCCXVII",817); 
		romanos.put("DCCCXVIII",818); 
		romanos.put("DCCCXIX",819); 
		romanos.put("DCCCXX",820); 
		romanos.put("DCCCXXI",821); 
		romanos.put("DCCCXXII",822); 
		romanos.put("DCCCXXIII",823); 
		romanos.put("DCCCXXIV",824); 
		romanos.put("DCCCXXV",825); 
		romanos.put("DCCCXXVI",826); 
		romanos.put("DCCCXXVII",827); 
		romanos.put("DCCCXXVIII",828); 
		romanos.put("DCCCXXIX",829); 
		romanos.put("DCCCXXX",830); 
		romanos.put("DCCCXXXI",831); 
		romanos.put("DCCCXXXII",832); 
		romanos.put("DCCCXXXIII",833); 
		romanos.put("DCCCXXXIV",834); 
		romanos.put("DCCCXXXV",835); 
		romanos.put("DCCCXXXVI",836); 
		romanos.put("DCCCXXXVII",837); 
		romanos.put("DCCCXXXVIII",838); 
		romanos.put("DCCCXXXIX",839); 
		romanos.put("DCCCXL",840); 
		romanos.put("DCCCXLI",841); 
		romanos.put("DCCCXLII",842); 
		romanos.put("DCCCXLIII",843); 
		romanos.put("DCCCXLIV",844); 
		romanos.put("DCCCXLV",845); 
		romanos.put("DCCCXLVI",846); 
		romanos.put("DCCCXLVII",847); 
		romanos.put("DCCCXLVIII",848); 
		romanos.put("DCCCXLIX",849); 
		romanos.put("DCCCL",850); 
		romanos.put("DCCCLI",851); 
		romanos.put("DCCCLII",852); 
		romanos.put("DCCCLIII",853); 
		romanos.put("DCCCLIV",854); 
		romanos.put("DCCCLV",855); 
		romanos.put("DCCCLVI",856); 
		romanos.put("DCCCLVII",857); 
		romanos.put("DCCCLVIII",858); 
		romanos.put("DCCCLIX",859); 
		romanos.put("DCCCLX",860); 
		romanos.put("DCCCLXI",861); 
		romanos.put("DCCCLXII",862); 
		romanos.put("DCCCLXIII",863); 
		romanos.put("DCCCLXIV",864); 
		romanos.put("DCCCLXV",865); 
		romanos.put("DCCCLXVI",866); 
		romanos.put("DCCCLXVII",867); 
		romanos.put("DCCCLXVIII",868); 
		romanos.put("DCCCLXIX",869); 
		romanos.put("DCCCLXX",870); 
		romanos.put("DCCCLXXI",871); 
		romanos.put("DCCCLXXII",872); 
		romanos.put("DCCCLXXIII",873); 
		romanos.put("DCCCLXXIV",874); 
		romanos.put("DCCCLXXV",875); 
		romanos.put("DCCCLXXVI",876); 
		romanos.put("DCCCLXXVII",877); 
		romanos.put("DCCCLXXVIII",878); 
		romanos.put("DCCCLXXIX",879); 
		romanos.put("DCCCLXXX",880); 
		romanos.put("DCCCLXXXI",881); 
		romanos.put("DCCCLXXXII",882); 
		romanos.put("DCCCLXXXIII",883); 
		romanos.put("DCCCLXXXIV",884); 
		romanos.put("DCCCLXXXV",885); 
		romanos.put("DCCCLXXXVI",886); 
		romanos.put("DCCCLXXXVII",887); 
		romanos.put("DCCCLXXXVIII",888); 
		romanos.put("DCCCLXXXIX",889); 
		romanos.put("DCCCXC",890); 
		romanos.put("DCCCXCI",891); 
		romanos.put("DCCCXCII",892); 
		romanos.put("DCCCXCIII",893); 
		romanos.put("DCCCXCIV",894); 
		romanos.put("DCCCXCV",895); 
		romanos.put("DCCCXCVI",896); 
		romanos.put("DCCCXCVII",897); 
		romanos.put("DCCCXCVIII",898); 
		romanos.put("DCCCXCIX",899); 
		romanos.put("CM",900); 
		romanos.put("CMI",901); 
		romanos.put("CMII",902); 
		romanos.put("CMIII",903); 
		romanos.put("CMIV",904); 
		romanos.put("CMV",905); 
		romanos.put("CMVI",906); 
		romanos.put("CMVII",907); 
		romanos.put("CMVIII",908); 
		romanos.put("CMIX",909); 
		romanos.put("CMX",910); 
		romanos.put("CMXI",911); 
		romanos.put("CMXII",912); 
		romanos.put("CMXIII",913); 
		romanos.put("CMXIV",914); 
		romanos.put("CMXV",915); 
		romanos.put("CMXVI",916); 
		romanos.put("CMXVII",917); 
		romanos.put("CMXVIII",918); 
		romanos.put("CMXIX",919); 
		romanos.put("CMXX",920); 
		romanos.put("CMXXI",921); 
		romanos.put("CMXXII",922); 
		romanos.put("CMXXIII",923); 
		romanos.put("CMXXIV",924); 
		romanos.put("CMXXV",925); 
		romanos.put("CMXXVI",926); 
		romanos.put("CMXXVII",927); 
		romanos.put("CMXXVIII",928); 
		romanos.put("CMXXIX",929); 
		romanos.put("CMXXX",930); 
		romanos.put("CMXXXI",931); 
		romanos.put("CMXXXII",932); 
		romanos.put("CMXXXIII",933); 
		romanos.put("CMXXXIV",934); 
		romanos.put("CMXXXV",935); 
		romanos.put("CMXXXVI",936); 
		romanos.put("CMXXXVII",937); 
		romanos.put("CMXXXVIII",938); 
		romanos.put("CMXXXIX",939); 
		romanos.put("CMXL",940); 
		romanos.put("CMXLI",941); 
		romanos.put("CMXLII",942); 
		romanos.put("CMXLIII",943); 
		romanos.put("CMXLIV",944); 
		romanos.put("CMXLV",945); 
		romanos.put("CMXLVI",946); 
		romanos.put("CMXLVII",947); 
		romanos.put("CMXLVIII",948); 
		romanos.put("CMXLIX",949); 
		romanos.put("CML",950); 
		romanos.put("CMLI",951); 
		romanos.put("CMLII",952); 
		romanos.put("CMLIII",953); 
		romanos.put("CMLIV",954); 
		romanos.put("CMLV",955); 
		romanos.put("CMLVI",956); 
		romanos.put("CMLVII",957); 
		romanos.put("CMLVIII",958); 
		romanos.put("CMLIX",959); 
		romanos.put("CMLX",960); 
		romanos.put("CMLXI",961); 
		romanos.put("CMLXII",962); 
		romanos.put("CMLXIII",963); 
		romanos.put("CMLXIV",964); 
		romanos.put("CMLXV",965); 
		romanos.put("CMLXVI",966); 
		romanos.put("CMLXVII",967); 
		romanos.put("CMLXVIII",968); 
		romanos.put("CMLXIX",969); 
		romanos.put("CMLXX",970); 
		romanos.put("CMLXXI",971); 
		romanos.put("CMLXXII",972); 
		romanos.put("CMLXXIII",973); 
		romanos.put("CMLXXIV",974); 
		romanos.put("CMLXXV",975); 
		romanos.put("CMLXXVI",976); 
		romanos.put("CMLXXVII",977); 
		romanos.put("CMLXXVIII",978); 
		romanos.put("CMLXXIX",979); 
		romanos.put("CMLXXX",980); 
		romanos.put("CMLXXXI",981); 
		romanos.put("CMLXXXII",982); 
		romanos.put("CMLXXXIII",983); 
		romanos.put("CMLXXXIV",984); 
		romanos.put("CMLXXXV",985); 
		romanos.put("CMLXXXVI",986); 
		romanos.put("CMLXXXVII",987); 
		romanos.put("CMLXXXVIII",988); 
		romanos.put("CMLXXXIX",989); 
		romanos.put("CMXC",990); 
		romanos.put("CMXCI",991); 
		romanos.put("CMXCII",992); 
		romanos.put("CMXCIII",993); 
		romanos.put("CMXCIV",994); 
		romanos.put("CMXCV",995); 
		romanos.put("CMXCVI",996); 
		romanos.put("CMXCVII",997); 
		romanos.put("CMXCVIII",998); 
		romanos.put("CMXCIX",999); 
		romanos.put("M",1000); 
		
		
		numeros.put(1, "I"); 
		numeros.put(2, "II"); 
		numeros.put(3, "III"); 
		numeros.put(4, "IV"); 
		numeros.put(5, "V"); 
		numeros.put(6, "VI"); 
		numeros.put(7, "VII"); 
		numeros.put(8, "VIII"); 
		numeros.put(9, "IX"); 
		numeros.put(10, "X"); 
		numeros.put(11, "XI"); 
		numeros.put(12, "XII"); 
		numeros.put(13, "XIII"); 
		numeros.put(14, "XIV"); 
		numeros.put(15, "XV"); 
		numeros.put(16, "XVI"); 
		numeros.put(17, "XVII"); 
		numeros.put(18, "XVIII"); 
		numeros.put(19, "XIX"); 
		numeros.put(20, "XX"); 
		numeros.put(21, "XXI"); 
		numeros.put(22, "XXII"); 
		numeros.put(23, "XXIII"); 
		numeros.put(24, "XXIV"); 
		numeros.put(25, "XXV"); 
		numeros.put(26, "XXVI"); 
		numeros.put(27, "XXVII"); 
		numeros.put(28, "XXVIII"); 
		numeros.put(29, "XXIX"); 
		numeros.put(30, "XXX"); 
		numeros.put(31, "XXXI"); 
		numeros.put(32, "XXXII"); 
		numeros.put(33, "XXXIII"); 
		numeros.put(34, "XXXIV"); 
		numeros.put(35, "XXXV"); 
		numeros.put(36, "XXXVI"); 
		numeros.put(37, "XXXVII"); 
		numeros.put(38, "XXXVIII"); 
		numeros.put(39, "XXXIX"); 
		numeros.put(40, "XL"); 
		numeros.put(41, "XLI"); 
		numeros.put(42, "XLII"); 
		numeros.put(43, "XLIII"); 
		numeros.put(44, "XLIV"); 
		numeros.put(45, "XLV"); 
		numeros.put(46, "XLVI"); 
		numeros.put(47, "XLVII"); 
		numeros.put(48, "XLVIII"); 
		numeros.put(49, "XLIX"); 
		numeros.put(50, "L"); 
		numeros.put(51, "LI"); 
		numeros.put(52, "LII"); 
		numeros.put(53, "LIII"); 
		numeros.put(54, "LIV"); 
		numeros.put(55, "LV"); 
		numeros.put(56, "LVI"); 
		numeros.put(57, "LVII"); 
		numeros.put(58, "LVIII"); 
		numeros.put(59, "LIX"); 
		numeros.put(60, "LX"); 
		numeros.put(61, "LXI"); 
		numeros.put(62, "LXII"); 
		numeros.put(63, "LXIII"); 
		numeros.put(64, "LXIV"); 
		numeros.put(65, "LXV"); 
		numeros.put(66, "LXVI"); 
		numeros.put(67, "LXVII"); 
		numeros.put(68, "LXVIII"); 
		numeros.put(69, "LXIX"); 
		numeros.put(70, "LXX"); 
		numeros.put(71, "LXXI"); 
		numeros.put(72, "LXXII"); 
		numeros.put(73, "LXXIII"); 
		numeros.put(74, "LXXIV"); 
		numeros.put(75, "LXXV"); 
		numeros.put(76, "LXXVI"); 
		numeros.put(77, "LXXVII"); 
		numeros.put(78, "LXXVIII"); 
		numeros.put(79, "LXXIX"); 
		numeros.put(80, "LXXX"); 
		numeros.put(81, "LXXXI"); 
		numeros.put(82, "LXXXII"); 
		numeros.put(83, "LXXXIII"); 
		numeros.put(84, "LXXXIV"); 
		numeros.put(85, "LXXXV"); 
		numeros.put(86, "LXXXVI"); 
		numeros.put(87, "LXXXVII"); 
		numeros.put(88, "LXXXVIII"); 
		numeros.put(89, "LXXXIX"); 
		numeros.put(90, "XC"); 
		numeros.put(91, "XCI"); 
		numeros.put(92, "XCII"); 
		numeros.put(93, "XCIII"); 
		numeros.put(94, "XCIV"); 
		numeros.put(95, "XCV"); 
		numeros.put(96, "XCVI"); 
		numeros.put(97, "XCVII"); 
		numeros.put(98, "XCVIII"); 
		numeros.put(99, "XCIX"); 
		numeros.put(100, "C"); 
		numeros.put(101, "CI"); 
		numeros.put(102, "CII"); 
		numeros.put(103, "CIII"); 
		numeros.put(104, "CIV"); 
		numeros.put(105, "CV"); 
		numeros.put(106, "CVI"); 
		numeros.put(107, "CVII"); 
		numeros.put(108, "CVIII"); 
		numeros.put(109, "CIX"); 
		numeros.put(110, "CX"); 
		numeros.put(111, "CXI"); 
		numeros.put(112, "CXII"); 
		numeros.put(113, "CXIII"); 
		numeros.put(114, "CXIV"); 
		numeros.put(115, "CXV"); 
		numeros.put(116, "CXVI"); 
		numeros.put(117, "CXVII"); 
		numeros.put(118, "CXVIII"); 
		numeros.put(119, "CXIX"); 
		numeros.put(120, "CXX"); 
		numeros.put(121, "CXXI"); 
		numeros.put(122, "CXXII"); 
		numeros.put(123, "CXXIII"); 
		numeros.put(124, "CXXIV"); 
		numeros.put(125, "CXXV"); 
		numeros.put(126, "CXXVI"); 
		numeros.put(127, "CXXVII"); 
		numeros.put(128, "CXXVIII"); 
		numeros.put(129, "CXXIX"); 
		numeros.put(130, "CXXX"); 
		numeros.put(131, "CXXXI"); 
		numeros.put(132, "CXXXII"); 
		numeros.put(133, "CXXXIII"); 
		numeros.put(134, "CXXXIV"); 
		numeros.put(135, "CXXXV"); 
		numeros.put(136, "CXXXVI"); 
		numeros.put(137, "CXXXVII"); 
		numeros.put(138, "CXXXVIII"); 
		numeros.put(139, "CXXXIX"); 
		numeros.put(140, "CXL"); 
		numeros.put(141, "CXLI"); 
		numeros.put(142, "CXLII"); 
		numeros.put(143, "CXLIII"); 
		numeros.put(144, "CXLIV"); 
		numeros.put(145, "CXLV"); 
		numeros.put(146, "CXLVI"); 
		numeros.put(147, "CXLVII"); 
		numeros.put(148, "CXLVIII"); 
		numeros.put(149, "CXLIX"); 
		numeros.put(150, "CL"); 
		numeros.put(151, "CLI"); 
		numeros.put(152, "CLII"); 
		numeros.put(153, "CLIII"); 
		numeros.put(154, "CLIV"); 
		numeros.put(155, "CLV"); 
		numeros.put(156, "CLVI"); 
		numeros.put(157, "CLVII"); 
		numeros.put(158, "CLVIII"); 
		numeros.put(159, "CLIX"); 
		numeros.put(160, "CLX"); 
		numeros.put(161, "CLXI"); 
		numeros.put(162, "CLXII"); 
		numeros.put(163, "CLXIII"); 
		numeros.put(164, "CLXIV"); 
		numeros.put(165, "CLXV"); 
		numeros.put(166, "CLXVI"); 
		numeros.put(167, "CLXVII"); 
		numeros.put(168, "CLXVIII"); 
		numeros.put(169, "CLXIX"); 
		numeros.put(170, "CLXX"); 
		numeros.put(171, "CLXXI"); 
		numeros.put(172, "CLXXII"); 
		numeros.put(173, "CLXXIII"); 
		numeros.put(174, "CLXXIV"); 
		numeros.put(175, "CLXXV"); 
		numeros.put(176, "CLXXVI"); 
		numeros.put(177, "CLXXVII"); 
		numeros.put(178, "CLXXVIII"); 
		numeros.put(179, "CLXXIX"); 
		numeros.put(180, "CLXXX"); 
		numeros.put(181, "CLXXXI"); 
		numeros.put(182, "CLXXXII"); 
		numeros.put(183, "CLXXXIII"); 
		numeros.put(184, "CLXXXIV"); 
		numeros.put(185, "CLXXXV"); 
		numeros.put(186, "CLXXXVI"); 
		numeros.put(187, "CLXXXVII"); 
		numeros.put(188, "CLXXXVIII"); 
		numeros.put(189, "CLXXXIX"); 
		numeros.put(190, "CXC"); 
		numeros.put(191, "CXCI"); 
		numeros.put(192, "CXCII"); 
		numeros.put(193, "CXCIII"); 
		numeros.put(194, "CXCIV"); 
		numeros.put(195, "CXCV"); 
		numeros.put(196, "CXCVI"); 
		numeros.put(197, "CXCVII"); 
		numeros.put(198, "CXCVIII"); 
		numeros.put(199, "CXCIX"); 
		numeros.put(200, "CC"); 
		numeros.put(201, "CCI"); 
		numeros.put(202, "CCII"); 
		numeros.put(203, "CCIII"); 
		numeros.put(204, "CCIV"); 
		numeros.put(205, "CCV"); 
		numeros.put(206, "CCVI"); 
		numeros.put(207, "CCVII"); 
		numeros.put(208, "CCVIII"); 
		numeros.put(209, "CCIX"); 
		numeros.put(210, "CCX"); 
		numeros.put(211, "CCXI"); 
		numeros.put(212, "CCXII"); 
		numeros.put(213, "CCXIII"); 
		numeros.put(214, "CCXIV"); 
		numeros.put(215, "CCXV"); 
		numeros.put(216, "CCXVI"); 
		numeros.put(217, "CCXVII"); 
		numeros.put(218, "CCXVIII"); 
		numeros.put(219, "CCXIX"); 
		numeros.put(220, "CCXX"); 
		numeros.put(221, "CCXXI"); 
		numeros.put(222, "CCXXII"); 
		numeros.put(223, "CCXXIII"); 
		numeros.put(224, "CCXXIV"); 
		numeros.put(225, "CCXXV"); 
		numeros.put(226, "CCXXVI"); 
		numeros.put(227, "CCXXVII"); 
		numeros.put(228, "CCXXVIII"); 
		numeros.put(229, "CCXXIX"); 
		numeros.put(230, "CCXXX"); 
		numeros.put(231, "CCXXXI"); 
		numeros.put(232, "CCXXXII"); 
		numeros.put(233, "CCXXXIII"); 
		numeros.put(234, "CCXXXIV"); 
		numeros.put(235, "CCXXXV"); 
		numeros.put(236, "CCXXXVI"); 
		numeros.put(237, "CCXXXVII"); 
		numeros.put(238, "CCXXXVIII"); 
		numeros.put(239, "CCXXXIX"); 
		numeros.put(240, "CCXL"); 
		numeros.put(241, "CCXLI"); 
		numeros.put(242, "CCXLII"); 
		numeros.put(243, "CCXLIII"); 
		numeros.put(244, "CCXLIV"); 
		numeros.put(245, "CCXLV"); 
		numeros.put(246, "CCXLVI"); 
		numeros.put(247, "CCXLVII"); 
		numeros.put(248, "CCXLVIII"); 
		numeros.put(249, "CCXLIX"); 
		numeros.put(250, "CCL"); 
		numeros.put(251, "CCLI"); 
		numeros.put(252, "CCLII"); 
		numeros.put(253, "CCLIII"); 
		numeros.put(254, "CCLIV"); 
		numeros.put(255, "CCLV"); 
		numeros.put(256, "CCLVI"); 
		numeros.put(257, "CCLVII"); 
		numeros.put(258, "CCLVIII"); 
		numeros.put(259, "CCLIX"); 
		numeros.put(260, "CCLX"); 
		numeros.put(261, "CCLXI"); 
		numeros.put(262, "CCLXII"); 
		numeros.put(263, "CCLXIII"); 
		numeros.put(264, "CCLXIV"); 
		numeros.put(265, "CCLXV"); 
		numeros.put(266, "CCLXVI"); 
		numeros.put(267, "CCLXVII"); 
		numeros.put(268, "CCLXVIII"); 
		numeros.put(269, "CCLXIX"); 
		numeros.put(270, "CCLXX"); 
		numeros.put(271, "CCLXXI"); 
		numeros.put(272, "CCLXXII"); 
		numeros.put(273, "CCLXXIII"); 
		numeros.put(274, "CCLXXIV"); 
		numeros.put(275, "CCLXXV"); 
		numeros.put(276, "CCLXXVI"); 
		numeros.put(277, "CCLXXVII"); 
		numeros.put(278, "CCLXXVIII"); 
		numeros.put(279, "CCLXXIX"); 
		numeros.put(280, "CCLXXX"); 
		numeros.put(281, "CCLXXXI"); 
		numeros.put(282, "CCLXXXII"); 
		numeros.put(283, "CCLXXXIII"); 
		numeros.put(284, "CCLXXXIV"); 
		numeros.put(285, "CCLXXXV"); 
		numeros.put(286, "CCLXXXVI"); 
		numeros.put(287, "CCLXXXVII"); 
		numeros.put(288, "CCLXXXVIII"); 
		numeros.put(289, "CCLXXXIX"); 
		numeros.put(290, "CCXC"); 
		numeros.put(291, "CCXCI"); 
		numeros.put(292, "CCXCII"); 
		numeros.put(293, "CCXCIII"); 
		numeros.put(294, "CCXCIV"); 
		numeros.put(295, "CCXCV"); 
		numeros.put(296, "CCXCVI"); 
		numeros.put(297, "CCXCVII"); 
		numeros.put(298, "CCXCVIII"); 
		numeros.put(299, "CCXCIX"); 
		numeros.put(300, "CCC"); 
		numeros.put(301, "CCCI"); 
		numeros.put(302, "CCCII"); 
		numeros.put(303, "CCCIII"); 
		numeros.put(304, "CCCIV"); 
		numeros.put(305, "CCCV"); 
		numeros.put(306, "CCCVI"); 
		numeros.put(307, "CCCVII"); 
		numeros.put(308, "CCCVIII"); 
		numeros.put(309, "CCCIX"); 
		numeros.put(310, "CCCX"); 
		numeros.put(311, "CCCXI"); 
		numeros.put(312, "CCCXII"); 
		numeros.put(313, "CCCXIII"); 
		numeros.put(314, "CCCXIV"); 
		numeros.put(315, "CCCXV"); 
		numeros.put(316, "CCCXVI"); 
		numeros.put(317, "CCCXVII"); 
		numeros.put(318, "CCCXVIII"); 
		numeros.put(319, "CCCXIX"); 
		numeros.put(320, "CCCXX"); 
		numeros.put(321, "CCCXXI"); 
		numeros.put(322, "CCCXXII"); 
		numeros.put(323, "CCCXXIII"); 
		numeros.put(324, "CCCXXIV"); 
		numeros.put(325, "CCCXXV"); 
		numeros.put(326, "CCCXXVI"); 
		numeros.put(327, "CCCXXVII"); 
		numeros.put(328, "CCCXXVIII"); 
		numeros.put(329, "CCCXXIX"); 
		numeros.put(330, "CCCXXX"); 
		numeros.put(331, "CCCXXXI"); 
		numeros.put(332, "CCCXXXII"); 
		numeros.put(333, "CCCXXXIII"); 
		numeros.put(334, "CCCXXXIV"); 
		numeros.put(335, "CCCXXXV"); 
		numeros.put(336, "CCCXXXVI"); 
		numeros.put(337, "CCCXXXVII"); 
		numeros.put(338, "CCCXXXVIII"); 
		numeros.put(339, "CCCXXXIX"); 
		numeros.put(340, "CCCXL"); 
		numeros.put(341, "CCCXLI"); 
		numeros.put(342, "CCCXLII"); 
		numeros.put(343, "CCCXLIII"); 
		numeros.put(344, "CCCXLIV"); 
		numeros.put(345, "CCCXLV"); 
		numeros.put(346, "CCCXLVI"); 
		numeros.put(347, "CCCXLVII"); 
		numeros.put(348, "CCCXLVIII"); 
		numeros.put(349, "CCCXLIX"); 
		numeros.put(350, "CCCL"); 
		numeros.put(351, "CCCLI"); 
		numeros.put(352, "CCCLII"); 
		numeros.put(353, "CCCLIII"); 
		numeros.put(354, "CCCLIV"); 
		numeros.put(355, "CCCLV"); 
		numeros.put(356, "CCCLVI"); 
		numeros.put(357, "CCCLVII"); 
		numeros.put(358, "CCCLVIII"); 
		numeros.put(359, "CCCLIX"); 
		numeros.put(360, "CCCLX"); 
		numeros.put(361, "CCCLXI"); 
		numeros.put(362, "CCCLXII"); 
		numeros.put(363, "CCCLXIII"); 
		numeros.put(364, "CCCLXIV"); 
		numeros.put(365, "CCCLXV"); 
		numeros.put(366, "CCCLXVI"); 
		numeros.put(367, "CCCLXVII"); 
		numeros.put(368, "CCCLXVIII"); 
		numeros.put(369, "CCCLXIX"); 
		numeros.put(370, "CCCLXX"); 
		numeros.put(371, "CCCLXXI"); 
		numeros.put(372, "CCCLXXII"); 
		numeros.put(373, "CCCLXXIII"); 
		numeros.put(374, "CCCLXXIV"); 
		numeros.put(375, "CCCLXXV"); 
		numeros.put(376, "CCCLXXVI"); 
		numeros.put(377, "CCCLXXVII"); 
		numeros.put(378, "CCCLXXVIII"); 
		numeros.put(379, "CCCLXXIX"); 
		numeros.put(380, "CCCLXXX"); 
		numeros.put(381, "CCCLXXXI"); 
		numeros.put(382, "CCCLXXXII"); 
		numeros.put(383, "CCCLXXXIII"); 
		numeros.put(384, "CCCLXXXIV"); 
		numeros.put(385, "CCCLXXXV"); 
		numeros.put(386, "CCCLXXXVI"); 
		numeros.put(387, "CCCLXXXVII"); 
		numeros.put(388, "CCCLXXXVIII"); 
		numeros.put(389, "CCCLXXXIX"); 
		numeros.put(390, "CCCXC"); 
		numeros.put(391, "CCCXCI"); 
		numeros.put(392, "CCCXCII"); 
		numeros.put(393, "CCCXCIII"); 
		numeros.put(394, "CCCXCIV"); 
		numeros.put(395, "CCCXCV"); 
		numeros.put(396, "CCCXCVI"); 
		numeros.put(397, "CCCXCVII"); 
		numeros.put(398, "CCCXCVIII"); 
		numeros.put(399, "CCCXCIX"); 
		numeros.put(400, "CD"); 
		numeros.put(401, "CDI"); 
		numeros.put(402, "CDII"); 
		numeros.put(403, "CDIII"); 
		numeros.put(404, "CDIV"); 
		numeros.put(405, "CDV"); 
		numeros.put(406, "CDVI"); 
		numeros.put(407, "CDVII"); 
		numeros.put(408, "CDVIII"); 
		numeros.put(409, "CDIX"); 
		numeros.put(410, "CDX"); 
		numeros.put(411, "CDXI"); 
		numeros.put(412, "CDXII"); 
		numeros.put(413, "CDXIII"); 
		numeros.put(414, "CDXIV"); 
		numeros.put(415, "CDXV"); 
		numeros.put(416, "CDXVI"); 
		numeros.put(417, "CDXVII"); 
		numeros.put(418, "CDXVIII"); 
		numeros.put(419, "CDXIX"); 
		numeros.put(420, "CDXX"); 
		numeros.put(421, "CDXXI"); 
		numeros.put(422, "CDXXII"); 
		numeros.put(423, "CDXXIII"); 
		numeros.put(424, "CDXXIV"); 
		numeros.put(425, "CDXXV"); 
		numeros.put(426, "CDXXVI"); 
		numeros.put(427, "CDXXVII"); 
		numeros.put(428, "CDXXVIII"); 
		numeros.put(429, "CDXXIX"); 
		numeros.put(430, "CDXXX"); 
		numeros.put(431, "CDXXXI"); 
		numeros.put(432, "CDXXXII"); 
		numeros.put(433, "CDXXXIII"); 
		numeros.put(434, "CDXXXIV"); 
		numeros.put(435, "CDXXXV"); 
		numeros.put(436, "CDXXXVI"); 
		numeros.put(437, "CDXXXVII"); 
		numeros.put(438, "CDXXXVIII"); 
		numeros.put(439, "CDXXXIX"); 
		numeros.put(440, "CDXL"); 
		numeros.put(441, "CDXLI"); 
		numeros.put(442, "CDXLII"); 
		numeros.put(443, "CDXLIII"); 
		numeros.put(444, "CDXLIV"); 
		numeros.put(445, "CDXLV"); 
		numeros.put(446, "CDXLVI"); 
		numeros.put(447, "CDXLVII"); 
		numeros.put(448, "CDXLVIII"); 
		numeros.put(449, "CDXLIX"); 
		numeros.put(450, "CDL"); 
		numeros.put(451, "CDLI"); 
		numeros.put(452, "CDLII"); 
		numeros.put(453, "CDLIII"); 
		numeros.put(454, "CDLIV"); 
		numeros.put(455, "CDLV"); 
		numeros.put(456, "CDLVI"); 
		numeros.put(457, "CDLVII"); 
		numeros.put(458, "CDLVIII"); 
		numeros.put(459, "CDLIX"); 
		numeros.put(460, "CDLX"); 
		numeros.put(461, "CDLXI"); 
		numeros.put(462, "CDLXII"); 
		numeros.put(463, "CDLXIII"); 
		numeros.put(464, "CDLXIV"); 
		numeros.put(465, "CDLXV"); 
		numeros.put(466, "CDLXVI"); 
		numeros.put(467, "CDLXVII"); 
		numeros.put(468, "CDLXVIII"); 
		numeros.put(469, "CDLXIX"); 
		numeros.put(470, "CDLXX"); 
		numeros.put(471, "CDLXXI"); 
		numeros.put(472, "CDLXXII"); 
		numeros.put(473, "CDLXXIII"); 
		numeros.put(474, "CDLXXIV"); 
		numeros.put(475, "CDLXXV"); 
		numeros.put(476, "CDLXXVI"); 
		numeros.put(477, "CDLXXVII"); 
		numeros.put(478, "CDLXXVIII"); 
		numeros.put(479, "CDLXXIX"); 
		numeros.put(480, "CDLXXX"); 
		numeros.put(481, "CDLXXXI"); 
		numeros.put(482, "CDLXXXII"); 
		numeros.put(483, "CDLXXXIII"); 
		numeros.put(484, "CDLXXXIV"); 
		numeros.put(485, "CDLXXXV"); 
		numeros.put(486, "CDLXXXVI"); 
		numeros.put(487, "CDLXXXVII"); 
		numeros.put(488, "CDLXXXVIII"); 
		numeros.put(489, "CDLXXXIX"); 
		numeros.put(490, "CDXC"); 
		numeros.put(491, "CDXCI"); 
		numeros.put(492, "CDXCII"); 
		numeros.put(493, "CDXCIII"); 
		numeros.put(494, "CDXCIV"); 
		numeros.put(495, "CDXCV"); 
		numeros.put(496, "CDXCVI"); 
		numeros.put(497, "CDXCVII"); 
		numeros.put(498, "CDXCVIII"); 
		numeros.put(499, "CDXCIX"); 
		numeros.put(500, "D"); 
		numeros.put(501, "DI"); 
		numeros.put(502, "DII"); 
		numeros.put(503, "DIII"); 
		numeros.put(504, "DIV"); 
		numeros.put(505, "DV"); 
		numeros.put(506, "DVI"); 
		numeros.put(507, "DVII"); 
		numeros.put(508, "DVIII"); 
		numeros.put(509, "DIX"); 
		numeros.put(510, "DX"); 
		numeros.put(511, "DXI"); 
		numeros.put(512, "DXII"); 
		numeros.put(513, "DXIII"); 
		numeros.put(514, "DXIV"); 
		numeros.put(515, "DXV"); 
		numeros.put(516, "DXVI"); 
		numeros.put(517, "DXVII"); 
		numeros.put(518, "DXVIII"); 
		numeros.put(519, "DXIX"); 
		numeros.put(520, "DXX"); 
		numeros.put(521, "DXXI"); 
		numeros.put(522, "DXXII"); 
		numeros.put(523, "DXXIII"); 
		numeros.put(524, "DXXIV"); 
		numeros.put(525, "DXXV"); 
		numeros.put(526, "DXXVI"); 
		numeros.put(527, "DXXVII"); 
		numeros.put(528, "DXXVIII"); 
		numeros.put(529, "DXXIX"); 
		numeros.put(530, "DXXX"); 
		numeros.put(531, "DXXXI"); 
		numeros.put(532, "DXXXII"); 
		numeros.put(533, "DXXXIII"); 
		numeros.put(534, "DXXXIV"); 
		numeros.put(535, "DXXXV"); 
		numeros.put(536, "DXXXVI"); 
		numeros.put(537, "DXXXVII"); 
		numeros.put(538, "DXXXVIII"); 
		numeros.put(539, "DXXXIX"); 
		numeros.put(540, "DXL"); 
		numeros.put(541, "DXLI"); 
		numeros.put(542, "DXLII"); 
		numeros.put(543, "DXLIII"); 
		numeros.put(544, "DXLIV"); 
		numeros.put(545, "DXLV"); 
		numeros.put(546, "DXLVI"); 
		numeros.put(547, "DXLVII"); 
		numeros.put(548, "DXLVIII"); 
		numeros.put(549, "DXLIX"); 
		numeros.put(550, "DL"); 
		numeros.put(551, "DLI"); 
		numeros.put(552, "DLII"); 
		numeros.put(553, "DLIII"); 
		numeros.put(554, "DLIV"); 
		numeros.put(555, "DLV"); 
		numeros.put(556, "DLVI"); 
		numeros.put(557, "DLVII"); 
		numeros.put(558, "DLVIII"); 
		numeros.put(559, "DLIX"); 
		numeros.put(560, "DLX"); 
		numeros.put(561, "DLXI"); 
		numeros.put(562, "DLXII"); 
		numeros.put(563, "DLXIII"); 
		numeros.put(564, "DLXIV"); 
		numeros.put(565, "DLXV"); 
		numeros.put(566, "DLXVI"); 
		numeros.put(567, "DLXVII"); 
		numeros.put(568, "DLXVIII"); 
		numeros.put(569, "DLXIX"); 
		numeros.put(570, "DLXX"); 
		numeros.put(571, "DLXXI"); 
		numeros.put(572, "DLXXII"); 
		numeros.put(573, "DLXXIII"); 
		numeros.put(574, "DLXXIV"); 
		numeros.put(575, "DLXXV"); 
		numeros.put(576, "DLXXVI"); 
		numeros.put(577, "DLXXVII"); 
		numeros.put(578, "DLXXVIII"); 
		numeros.put(579, "DLXXIX"); 
		numeros.put(580, "DLXXX"); 
		numeros.put(581, "DLXXXI"); 
		numeros.put(582, "DLXXXII"); 
		numeros.put(583, "DLXXXIII"); 
		numeros.put(584, "DLXXXIV"); 
		numeros.put(585, "DLXXXV"); 
		numeros.put(586, "DLXXXVI"); 
		numeros.put(587, "DLXXXVII"); 
		numeros.put(588, "DLXXXVIII"); 
		numeros.put(589, "DLXXXIX"); 
		numeros.put(590, "DXC"); 
		numeros.put(591, "DXCI"); 
		numeros.put(592, "DXCII"); 
		numeros.put(593, "DXCIII"); 
		numeros.put(594, "DXCIV"); 
		numeros.put(595, "DXCV"); 
		numeros.put(596, "DXCVI"); 
		numeros.put(597, "DXCVII"); 
		numeros.put(598, "DXCVIII"); 
		numeros.put(599, "DXCIX"); 
		numeros.put(600, "DC"); 
		numeros.put(601, "DCI"); 
		numeros.put(602, "DCII"); 
		numeros.put(603, "DCIII"); 
		numeros.put(604, "DCIV"); 
		numeros.put(605, "DCV"); 
		numeros.put(606, "DCVI"); 
		numeros.put(607, "DCVII"); 
		numeros.put(608, "DCVIII"); 
		numeros.put(609, "DCIX"); 
		numeros.put(610, "DCX"); 
		numeros.put(611, "DCXI"); 
		numeros.put(612, "DCXII"); 
		numeros.put(613, "DCXIII"); 
		numeros.put(614, "DCXIV"); 
		numeros.put(615, "DCXV"); 
		numeros.put(616, "DCXVI"); 
		numeros.put(617, "DCXVII"); 
		numeros.put(618, "DCXVIII"); 
		numeros.put(619, "DCXIX"); 
		numeros.put(620, "DCXX"); 
		numeros.put(621, "DCXXI"); 
		numeros.put(622, "DCXXII"); 
		numeros.put(623, "DCXXIII"); 
		numeros.put(624, "DCXXIV"); 
		numeros.put(625, "DCXXV"); 
		numeros.put(626, "DCXXVI"); 
		numeros.put(627, "DCXXVII"); 
		numeros.put(628, "DCXXVIII"); 
		numeros.put(629, "DCXXIX"); 
		numeros.put(630, "DCXXX"); 
		numeros.put(631, "DCXXXI"); 
		numeros.put(632, "DCXXXII"); 
		numeros.put(633, "DCXXXIII"); 
		numeros.put(634, "DCXXXIV"); 
		numeros.put(635, "DCXXXV"); 
		numeros.put(636, "DCXXXVI"); 
		numeros.put(637, "DCXXXVII"); 
		numeros.put(638, "DCXXXVIII"); 
		numeros.put(639, "DCXXXIX"); 
		numeros.put(640, "DCXL"); 
		numeros.put(641, "DCXLI"); 
		numeros.put(642, "DCXLII"); 
		numeros.put(643, "DCXLIII"); 
		numeros.put(644, "DCXLIV"); 
		numeros.put(645, "DCXLV"); 
		numeros.put(646, "DCXLVI"); 
		numeros.put(647, "DCXLVII"); 
		numeros.put(648, "DCXLVIII"); 
		numeros.put(649, "DCXLIX"); 
		numeros.put(650, "DCL"); 
		numeros.put(651, "DCLI"); 
		numeros.put(652, "DCLII"); 
		numeros.put(653, "DCLIII"); 
		numeros.put(654, "DCLIV"); 
		numeros.put(655, "DCLV"); 
		numeros.put(656, "DCLVI"); 
		numeros.put(657, "DCLVII"); 
		numeros.put(658, "DCLVIII"); 
		numeros.put(659, "DCLIX"); 
		numeros.put(660, "DCLX"); 
		numeros.put(661, "DCLXI"); 
		numeros.put(662, "DCLXII"); 
		numeros.put(663, "DCLXIII"); 
		numeros.put(664, "DCLXIV"); 
		numeros.put(665, "DCLXV"); 
		numeros.put(666, "DCLXVI"); 
		numeros.put(667, "DCLXVII"); 
		numeros.put(668, "DCLXVIII"); 
		numeros.put(669, "DCLXIX"); 
		numeros.put(670, "DCLXX"); 
		numeros.put(671, "DCLXXI"); 
		numeros.put(672, "DCLXXII"); 
		numeros.put(673, "DCLXXIII"); 
		numeros.put(674, "DCLXXIV"); 
		numeros.put(675, "DCLXXV"); 
		numeros.put(676, "DCLXXVI"); 
		numeros.put(677, "DCLXXVII"); 
		numeros.put(678, "DCLXXVIII"); 
		numeros.put(679, "DCLXXIX"); 
		numeros.put(680, "DCLXXX"); 
		numeros.put(681, "DCLXXXI"); 
		numeros.put(682, "DCLXXXII"); 
		numeros.put(683, "DCLXXXIII"); 
		numeros.put(684, "DCLXXXIV"); 
		numeros.put(685, "DCLXXXV"); 
		numeros.put(686, "DCLXXXVI"); 
		numeros.put(687, "DCLXXXVII"); 
		numeros.put(688, "DCLXXXVIII"); 
		numeros.put(689, "DCLXXXIX"); 
		numeros.put(690, "DCXC"); 
		numeros.put(691, "DCXCI"); 
		numeros.put(692, "DCXCII"); 
		numeros.put(693, "DCXCIII"); 
		numeros.put(694, "DCXCIV"); 
		numeros.put(695, "DCXCV"); 
		numeros.put(696, "DCXCVI"); 
		numeros.put(697, "DCXCVII"); 
		numeros.put(698, "DCXCVIII"); 
		numeros.put(699, "DCXCIX"); 
		numeros.put(700, "DCC"); 
		numeros.put(701, "DCCI"); 
		numeros.put(702, "DCCII"); 
		numeros.put(703, "DCCIII"); 
		numeros.put(704, "DCCIV"); 
		numeros.put(705, "DCCV"); 
		numeros.put(706, "DCCVI"); 
		numeros.put(707, "DCCVII"); 
		numeros.put(708, "DCCVIII"); 
		numeros.put(709, "DCCIX"); 
		numeros.put(710, "DCCX"); 
		numeros.put(711, "DCCXI"); 
		numeros.put(712, "DCCXII"); 
		numeros.put(713, "DCCXIII"); 
		numeros.put(714, "DCCXIV"); 
		numeros.put(715, "DCCXV"); 
		numeros.put(716, "DCCXVI"); 
		numeros.put(717, "DCCXVII"); 
		numeros.put(718, "DCCXVIII"); 
		numeros.put(719, "DCCXIX"); 
		numeros.put(720, "DCCXX"); 
		numeros.put(721, "DCCXXI"); 
		numeros.put(722, "DCCXXII"); 
		numeros.put(723, "DCCXXIII"); 
		numeros.put(724, "DCCXXIV"); 
		numeros.put(725, "DCCXXV"); 
		numeros.put(726, "DCCXXVI"); 
		numeros.put(727, "DCCXXVII"); 
		numeros.put(728, "DCCXXVIII"); 
		numeros.put(729, "DCCXXIX"); 
		numeros.put(730, "DCCXXX"); 
		numeros.put(731, "DCCXXXI"); 
		numeros.put(732, "DCCXXXII"); 
		numeros.put(733, "DCCXXXIII"); 
		numeros.put(734, "DCCXXXIV"); 
		numeros.put(735, "DCCXXXV"); 
		numeros.put(736, "DCCXXXVI"); 
		numeros.put(737, "DCCXXXVII"); 
		numeros.put(738, "DCCXXXVIII"); 
		numeros.put(739, "DCCXXXIX"); 
		numeros.put(740, "DCCXL"); 
		numeros.put(741, "DCCXLI"); 
		numeros.put(742, "DCCXLII"); 
		numeros.put(743, "DCCXLIII"); 
		numeros.put(744, "DCCXLIV"); 
		numeros.put(745, "DCCXLV"); 
		numeros.put(746, "DCCXLVI"); 
		numeros.put(747, "DCCXLVII"); 
		numeros.put(748, "DCCXLVIII"); 
		numeros.put(749, "DCCXLIX"); 
		numeros.put(750, "DCCL"); 
		numeros.put(751, "DCCLI"); 
		numeros.put(752, "DCCLII"); 
		numeros.put(753, "DCCLIII"); 
		numeros.put(754, "DCCLIV"); 
		numeros.put(755, "DCCLV"); 
		numeros.put(756, "DCCLVI"); 
		numeros.put(757, "DCCLVII"); 
		numeros.put(758, "DCCLVIII"); 
		numeros.put(759, "DCCLIX"); 
		numeros.put(760, "DCCLX"); 
		numeros.put(761, "DCCLXI"); 
		numeros.put(762, "DCCLXII"); 
		numeros.put(763, "DCCLXIII"); 
		numeros.put(764, "DCCLXIV"); 
		numeros.put(765, "DCCLXV"); 
		numeros.put(766, "DCCLXVI"); 
		numeros.put(767, "DCCLXVII"); 
		numeros.put(768, "DCCLXVIII"); 
		numeros.put(769, "DCCLXIX"); 
		numeros.put(770, "DCCLXX"); 
		numeros.put(771, "DCCLXXI"); 
		numeros.put(772, "DCCLXXII"); 
		numeros.put(773, "DCCLXXIII"); 
		numeros.put(774, "DCCLXXIV"); 
		numeros.put(775, "DCCLXXV"); 
		numeros.put(776, "DCCLXXVI"); 
		numeros.put(777, "DCCLXXVII"); 
		numeros.put(778, "DCCLXXVIII"); 
		numeros.put(779, "DCCLXXIX"); 
		numeros.put(780, "DCCLXXX"); 
		numeros.put(781, "DCCLXXXI"); 
		numeros.put(782, "DCCLXXXII"); 
		numeros.put(783, "DCCLXXXIII"); 
		numeros.put(784, "DCCLXXXIV"); 
		numeros.put(785, "DCCLXXXV"); 
		numeros.put(786, "DCCLXXXVI"); 
		numeros.put(787, "DCCLXXXVII"); 
		numeros.put(788, "DCCLXXXVIII"); 
		numeros.put(789, "DCCLXXXIX"); 
		numeros.put(790, "DCCXC"); 
		numeros.put(791, "DCCXCI"); 
		numeros.put(792, "DCCXCII"); 
		numeros.put(793, "DCCXCIII"); 
		numeros.put(794, "DCCXCIV"); 
		numeros.put(795, "DCCXCV"); 
		numeros.put(796, "DCCXCVI"); 
		numeros.put(797, "DCCXCVII"); 
		numeros.put(798, "DCCXCVIII"); 
		numeros.put(799, "DCCXCIX"); 
		numeros.put(800, "DCCC"); 
		numeros.put(801, "DCCCI"); 
		numeros.put(802, "DCCCII"); 
		numeros.put(803, "DCCCIII"); 
		numeros.put(804, "DCCCIV"); 
		numeros.put(805, "DCCCV"); 
		numeros.put(806, "DCCCVI"); 
		numeros.put(807, "DCCCVII"); 
		numeros.put(808, "DCCCVIII"); 
		numeros.put(809, "DCCCIX"); 
		numeros.put(810, "DCCCX"); 
		numeros.put(811, "DCCCXI"); 
		numeros.put(812, "DCCCXII"); 
		numeros.put(813, "DCCCXIII"); 
		numeros.put(814, "DCCCXIV"); 
		numeros.put(815, "DCCCXV"); 
		numeros.put(816, "DCCCXVI"); 
		numeros.put(817, "DCCCXVII"); 
		numeros.put(818, "DCCCXVIII"); 
		numeros.put(819, "DCCCXIX"); 
		numeros.put(820, "DCCCXX"); 
		numeros.put(821, "DCCCXXI"); 
		numeros.put(822, "DCCCXXII"); 
		numeros.put(823, "DCCCXXIII"); 
		numeros.put(824, "DCCCXXIV"); 
		numeros.put(825, "DCCCXXV"); 
		numeros.put(826, "DCCCXXVI"); 
		numeros.put(827, "DCCCXXVII"); 
		numeros.put(828, "DCCCXXVIII"); 
		numeros.put(829, "DCCCXXIX"); 
		numeros.put(830, "DCCCXXX"); 
		numeros.put(831, "DCCCXXXI"); 
		numeros.put(832, "DCCCXXXII"); 
		numeros.put(833, "DCCCXXXIII"); 
		numeros.put(834, "DCCCXXXIV"); 
		numeros.put(835, "DCCCXXXV"); 
		numeros.put(836, "DCCCXXXVI"); 
		numeros.put(837, "DCCCXXXVII"); 
		numeros.put(838, "DCCCXXXVIII"); 
		numeros.put(839, "DCCCXXXIX"); 
		numeros.put(840, "DCCCXL"); 
		numeros.put(841, "DCCCXLI"); 
		numeros.put(842, "DCCCXLII"); 
		numeros.put(843, "DCCCXLIII"); 
		numeros.put(844, "DCCCXLIV"); 
		numeros.put(845, "DCCCXLV"); 
		numeros.put(846, "DCCCXLVI"); 
		numeros.put(847, "DCCCXLVII"); 
		numeros.put(848, "DCCCXLVIII"); 
		numeros.put(849, "DCCCXLIX"); 
		numeros.put(850, "DCCCL"); 
		numeros.put(851, "DCCCLI"); 
		numeros.put(852, "DCCCLII"); 
		numeros.put(853, "DCCCLIII"); 
		numeros.put(854, "DCCCLIV"); 
		numeros.put(855, "DCCCLV"); 
		numeros.put(856, "DCCCLVI"); 
		numeros.put(857, "DCCCLVII"); 
		numeros.put(858, "DCCCLVIII"); 
		numeros.put(859, "DCCCLIX"); 
		numeros.put(860, "DCCCLX"); 
		numeros.put(861, "DCCCLXI"); 
		numeros.put(862, "DCCCLXII"); 
		numeros.put(863, "DCCCLXIII"); 
		numeros.put(864, "DCCCLXIV"); 
		numeros.put(865, "DCCCLXV"); 
		numeros.put(866, "DCCCLXVI"); 
		numeros.put(867, "DCCCLXVII"); 
		numeros.put(868, "DCCCLXVIII"); 
		numeros.put(869, "DCCCLXIX"); 
		numeros.put(870, "DCCCLXX"); 
		numeros.put(871, "DCCCLXXI"); 
		numeros.put(872, "DCCCLXXII"); 
		numeros.put(873, "DCCCLXXIII"); 
		numeros.put(874, "DCCCLXXIV"); 
		numeros.put(875, "DCCCLXXV"); 
		numeros.put(876, "DCCCLXXVI"); 
		numeros.put(877, "DCCCLXXVII"); 
		numeros.put(878, "DCCCLXXVIII"); 
		numeros.put(879, "DCCCLXXIX"); 
		numeros.put(880, "DCCCLXXX"); 
		numeros.put(881, "DCCCLXXXI"); 
		numeros.put(882, "DCCCLXXXII"); 
		numeros.put(883, "DCCCLXXXIII"); 
		numeros.put(884, "DCCCLXXXIV"); 
		numeros.put(885, "DCCCLXXXV"); 
		numeros.put(886, "DCCCLXXXVI"); 
		numeros.put(887, "DCCCLXXXVII"); 
		numeros.put(888, "DCCCLXXXVIII"); 
		numeros.put(889, "DCCCLXXXIX"); 
		numeros.put(890, "DCCCXC"); 
		numeros.put(891, "DCCCXCI"); 
		numeros.put(892, "DCCCXCII"); 
		numeros.put(893, "DCCCXCIII"); 
		numeros.put(894, "DCCCXCIV"); 
		numeros.put(895, "DCCCXCV"); 
		numeros.put(896, "DCCCXCVI"); 
		numeros.put(897, "DCCCXCVII"); 
		numeros.put(898, "DCCCXCVIII"); 
		numeros.put(899, "DCCCXCIX"); 
		numeros.put(900, "CM"); 
		numeros.put(901, "CMI"); 
		numeros.put(902, "CMII"); 
		numeros.put(903, "CMIII"); 
		numeros.put(904, "CMIV"); 
		numeros.put(905, "CMV"); 
		numeros.put(906, "CMVI"); 
		numeros.put(907, "CMVII"); 
		numeros.put(908, "CMVIII"); 
		numeros.put(909, "CMIX"); 
		numeros.put(910, "CMX"); 
		numeros.put(911, "CMXI"); 
		numeros.put(912, "CMXII"); 
		numeros.put(913, "CMXIII"); 
		numeros.put(914, "CMXIV"); 
		numeros.put(915, "CMXV"); 
		numeros.put(916, "CMXVI"); 
		numeros.put(917, "CMXVII"); 
		numeros.put(918, "CMXVIII"); 
		numeros.put(919, "CMXIX"); 
		numeros.put(920, "CMXX"); 
		numeros.put(921, "CMXXI"); 
		numeros.put(922, "CMXXII"); 
		numeros.put(923, "CMXXIII"); 
		numeros.put(924, "CMXXIV"); 
		numeros.put(925, "CMXXV"); 
		numeros.put(926, "CMXXVI"); 
		numeros.put(927, "CMXXVII"); 
		numeros.put(928, "CMXXVIII"); 
		numeros.put(929, "CMXXIX"); 
		numeros.put(930, "CMXXX"); 
		numeros.put(931, "CMXXXI"); 
		numeros.put(932, "CMXXXII"); 
		numeros.put(933, "CMXXXIII"); 
		numeros.put(934, "CMXXXIV"); 
		numeros.put(935, "CMXXXV"); 
		numeros.put(936, "CMXXXVI"); 
		numeros.put(937, "CMXXXVII"); 
		numeros.put(938, "CMXXXVIII"); 
		numeros.put(939, "CMXXXIX"); 
		numeros.put(940, "CMXL"); 
		numeros.put(941, "CMXLI"); 
		numeros.put(942, "CMXLII"); 
		numeros.put(943, "CMXLIII"); 
		numeros.put(944, "CMXLIV"); 
		numeros.put(945, "CMXLV"); 
		numeros.put(946, "CMXLVI"); 
		numeros.put(947, "CMXLVII"); 
		numeros.put(948, "CMXLVIII"); 
		numeros.put(949, "CMXLIX"); 
		numeros.put(950, "CML"); 
		numeros.put(951, "CMLI"); 
		numeros.put(952, "CMLII"); 
		numeros.put(953, "CMLIII"); 
		numeros.put(954, "CMLIV"); 
		numeros.put(955, "CMLV"); 
		numeros.put(956, "CMLVI"); 
		numeros.put(957, "CMLVII"); 
		numeros.put(958, "CMLVIII"); 
		numeros.put(959, "CMLIX"); 
		numeros.put(960, "CMLX"); 
		numeros.put(961, "CMLXI"); 
		numeros.put(962, "CMLXII"); 
		numeros.put(963, "CMLXIII"); 
		numeros.put(964, "CMLXIV"); 
		numeros.put(965, "CMLXV"); 
		numeros.put(966, "CMLXVI"); 
		numeros.put(967, "CMLXVII"); 
		numeros.put(968, "CMLXVIII"); 
		numeros.put(969, "CMLXIX"); 
		numeros.put(970, "CMLXX"); 
		numeros.put(971, "CMLXXI"); 
		numeros.put(972, "CMLXXII"); 
		numeros.put(973, "CMLXXIII"); 
		numeros.put(974, "CMLXXIV"); 
		numeros.put(975, "CMLXXV"); 
		numeros.put(976, "CMLXXVI"); 
		numeros.put(977, "CMLXXVII"); 
		numeros.put(978, "CMLXXVIII"); 
		numeros.put(979, "CMLXXIX"); 
		numeros.put(980, "CMLXXX"); 
		numeros.put(981, "CMLXXXI"); 
		numeros.put(982, "CMLXXXII"); 
		numeros.put(983, "CMLXXXIII"); 
		numeros.put(984, "CMLXXXIV"); 
		numeros.put(985, "CMLXXXV"); 
		numeros.put(986, "CMLXXXVI"); 
		numeros.put(987, "CMLXXXVII"); 
		numeros.put(988, "CMLXXXVIII"); 
		numeros.put(989, "CMLXXXIX"); 
		numeros.put(990, "CMXC"); 
		numeros.put(991, "CMXCI"); 
		numeros.put(992, "CMXCII"); 
		numeros.put(993, "CMXCIII"); 
		numeros.put(994, "CMXCIV"); 
		numeros.put(995, "CMXCV"); 
		numeros.put(996, "CMXCVI"); 
		numeros.put(997, "CMXCVII"); 
		numeros.put(998, "CMXCVIII"); 
		numeros.put(999, "CMXCIX"); 
		numeros.put(1000, "M"); 
	}
}
